### ISSUE TITLE
typo in file nomatim_reverse.go:89

### ISSUE THREAD

**Issue by xiconet** [grindhold/gominatim#6]
Hi,
Thanks for sharing your code. There seems to be a "typo" at line 89 of file `nominatim_reverse.go`, however:
We have
        ```s = s + fmt.Sprintf("&zoom&d", r.Zoom)```
instead of
	```s += fmt.Sprintf("&zoom=%d", r.Zoom)```

**Comment by grindhold** [comment]
fixed via merge of #7

**Comment by xiconet** [comment]
Great. Thanks again.
